function A = A_DAE(I,dlF,dlR,lF,lR,m,th)
%A_DAE
%    A = A_DAE(I,DLF,DLR,LF,LR,M,TH)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    12-Feb-2019 01:48:59

t2 = dlF+th;
t3 = dlR+th;
t4 = sin(t3);
t5 = cos(t3);
t6 = cos(dlR);
t7 = sin(t2);
t8 = cos(t2);
t9 = cos(dlF);
t10 = lF.*t9;
A = reshape([-m,0.0,0.0,-t4,-t7,0.0,-m,0.0,t5,t8,0.0,0.0,-I,-lR.*t6,t10,-t7,t8,t10,0.0,0.0,-t4,t5,-lR.*t6,0.0,0.0],[5,5]);
