function b = b_DAE(TF,TR,cF,cR,dlF,dlFd,dlR,dlRd,lF,lR,th,thd,xd,yd)
%B_DAE
%    B = B_DAE(TF,TR,CF,CR,DLF,DLFD,DLR,DLRD,LF,LR,TH,THD,XD,YD)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    12-Feb-2019 01:48:59

t2 = th.*2.0;
t3 = dlF.*2.0;
t4 = t2+t3;
t5 = dlR.*2.0;
t6 = t2+t5;
t7 = sin(th);
t8 = dlF+th;
t9 = dlR+th;
t10 = cos(t4);
t11 = cos(t6);
t12 = sin(t4);
t13 = sin(t6);
t14 = cos(th);
t15 = t3+th;
t16 = t5+th;
t17 = lF.^2;
t18 = lR.^2;
t19 = cos(t15);
t20 = cos(t16);
t21 = sin(t15);
t22 = sin(t16);
t23 = cos(t9);
t24 = sin(t9);
t25 = sin(dlR);
t26 = cos(t8);
t27 = sin(t8);
t28 = sin(dlF);
b = [-TF.*t26-TR.*t23+(cF.*xd)./2.0+(cR.*xd)./2.0+(cF.*t10.*xd)./2.0+(cR.*t11.*xd)./2.0+(cF.*t12.*yd)./2.0+(cR.*t13.*yd)./2.0-(cF.*lF.*t7.*thd)./2.0+(cF.*lF.*t21.*thd)./2.0+(cR.*lR.*t7.*thd)./2.0-(cR.*lR.*t22.*thd)./2.0;-TF.*t27-TR.*t24+(cF.*yd)./2.0+(cR.*yd)./2.0+(cF.*t12.*xd)./2.0+(cR.*t13.*xd)./2.0-(cF.*t10.*yd)./2.0-(cR.*t11.*yd)./2.0+(cF.*lF.*t14.*thd)./2.0-(cF.*lF.*t19.*thd)./2.0-(cR.*lR.*t14.*thd)./2.0+(cR.*lR.*t20.*thd)./2.0;-TF.*lF.*t28+TR.*lR.*t25+(cF.*t17.*thd)./2.0+(cR.*t18.*thd)./2.0-(cF.*lF.*t7.*xd)./2.0+(cF.*lF.*t21.*xd)./2.0+(cR.*lR.*t7.*xd)./2.0-(cR.*lR.*t22.*xd)./2.0+(cF.*lF.*t14.*yd)./2.0-(cF.*lF.*t19.*yd)./2.0-(cR.*lR.*t14.*yd)./2.0+(cR.*lR.*t20.*yd)./2.0-(cF.*t17.*thd.*cos(t3))./2.0-(cR.*t18.*thd.*cos(t5))./2.0;dlRd.*t23.*xd+dlRd.*t24.*yd+t23.*thd.*xd+t24.*thd.*yd-dlRd.*lR.*t25.*thd;dlFd.*t26.*xd+dlFd.*t27.*yd+t26.*thd.*xd+t27.*thd.*yd+dlFd.*lF.*t28.*thd];
