function vRd = vRd(I,TF,TR,cF,cR,dlF,dlFd,dlR,dlRd,lF,lR,m,t,td,vR)
%VRD
%    VRD = VRD(I,TF,TR,CF,CR,DLF,DLFD,DLR,DLRD,LF,LR,M,T,TD,VR)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    27-Feb-2019 18:09:44

t2 = dlF-dlR;
t3 = cos(t2);
t4 = sin(dlF);
t8 = dlR+t;
t5 = cos(t8);
t6 = cos(dlF);
t7 = lF+lR;
t9 = sin(t8);
t10 = t6.^2;
t11 = t7.^2;
t12 = TR-cR.*vR;
t14 = dlF+t;
t13 = cos(t14);
t15 = sin(t14);
t16 = cos(dlR);
t17 = cF.*t3.*vR;
t18 = cF.*lF.*t4.*td;
t19 = cF.*lR.*t4.*td;
t20 = -TF+t17+t18+t19;
t21 = sin(t2);
t22 = cos(t);
t23 = dlFd.*t3.*vR;
t24 = dlFd.*lF.*t4.*td;
t25 = dlFd.*lR.*t4.*td;
t32 = dlRd.*t3.*vR;
t26 = t23+t24+t25-t32;
t27 = sin(t);
t28 = 1.0./t21;
t29 = td.^2;
t30 = 1.0./t6;
t31 = 1.0./t7;
t33 = lF.^2;
t34 = dlF.*2.0;
t35 = lR.^2;
t36 = cos(t34);
t37 = dlR.*2.0;
t38 = cos(t37);
t39 = t34-t37;
t40 = cos(t39);
vRd = ((I.*t21.*t26-t5.^2.*t10.*t11.*t12-t9.^2.*t10.*t11.*t12+t6.*t11.*t13.^2.*t16.*t20+t6.*t11.*t15.^2.*t16.*t20+m.*t6.*t7.*t21.*(lR.*t22+t6.*t7.*t9.*t28).*(dlRd.*t5.*vR-lR.*t27.*t29+t5.*td.*vR+lR.*t22.*t26.*t30.*t31)+m.*t6.*t7.*t21.*(lR.*t27-t5.*t6.*t7.*t28).*(dlRd.*t9.*vR+lR.*t22.*t29+t9.*td.*vR+lR.*t26.*t27.*t30.*t31)).*-2.0)./(I-I.*t40+m.*t33+m.*t35+lF.*lR.*m+m.*t33.*t36+m.*t35.*t38+lF.*lR.*m.*t36+lF.*lR.*m.*t38+lF.*lR.*m.*t40);
