function RKE = AMB_RKE(I11,I13,I22,I33,p,pd,s,sd)
%AMB_RKE
%    RKE = AMB_RKE(I11,I13,I22,I33,P,PD,S,SD)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    15-Apr-2019 17:27:24

t2 = cos(p);
t3 = t2.^2;
t4 = cos(s);
t5 = sin(p);
t6 = sin(s);
RKE = (sd.*(I22.*sd+I13.*pd.*t2-I22.*sd.*t3+I33.*sd.*t3))./2.0+(pd.*t4.*(I11.*pd.*t4+I13.*pd.*t5.*t6+I13.*sd.*t2.*t4-I22.*sd.*t2.*t5.*t6+I33.*sd.*t2.*t5.*t6))./2.0+(pd.*t6.*(I11.*pd.*t6-I13.*pd.*t4.*t5+I13.*sd.*t2.*t6+I22.*sd.*t2.*t4.*t5-I33.*sd.*t2.*t4.*t5))./2.0;
