function LKE = LKE(V,dlr,h,lR,m,p,pd,s,sd)
%LKE
%    LKE = LKE(V,DLR,H,LR,M,P,PD,S,SD)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    22-Apr-2019 17:55:04

t2 = cos(s);
t3 = sin(s);
t4 = cos(p);
t6 = sin(dlr);
t7 = cos(dlr);
t8 = sin(p);
t5 = V.*(t2.*t6+t3.*t4.*t7)+sd.*(lR.*t2+h.*t3.*t8)-h.*pd.*t2.*t4;
t9 = V.*(t3.*t6-t2.*t4.*t7)+sd.*(lR.*t3-h.*t2.*t8)-h.*pd.*t3.*t4;
LKE = (m.*(t5.^2+t9.^2+h.^2.*pd.^2.*t8.^2))./2.0;
