function PSId = PSIdot(V,dlf,dlr,lF,lR)
%PSIDOT
%    PSID = PSIDOT(V,DLF,DLR,LF,LR)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    17-Apr-2019 12:50:29

PSId = (V.*sin(dlf-dlr))./(cos(dlf).*(lF+lR));
